import { MaterialItem, MaterialGroup } from './types';

export const GAME_DURATION_SECONDS = 60;
export const MAX_LIVES = 3;

export const MATERIAL_DATA: MaterialItem[] = [
  // Polymer
  { id: 1, name: "ขวดน้ำพลาสติก", material: "PET", group: MaterialGroup.POLYMER },
  { id: 2, name: "กล่องใส่อาหารพลาสติก", material: "PP", group: MaterialGroup.POLYMER },
  { id: 3, name: "ฟิล์มยืด", material: "PE", group: MaterialGroup.POLYMER },
  { id: 4, name: "ถุงพลาสติก", material: "HDPE", group: MaterialGroup.POLYMER },
  { id: 5, name: "หลอดดูด", material: "PP", group: MaterialGroup.POLYMER },
  { id: 6, name: "ฝาขวด", material: "PE", group: MaterialGroup.POLYMER },
  { id: 7, name: "ด้ามปากกา", material: "ABS", group: MaterialGroup.POLYMER },
  { id: 8, name: "เคสโทรศัพท์", material: "TPU/ซิลิโคน", group: MaterialGroup.POLYMER },
  { id: 9, name: "แว่นตาว่ายน้ำ", material: "ยาง", group: MaterialGroup.POLYMER },
  { id: 10, name: "ยางลบ", material: "ยางสังเคราะห์", group: MaterialGroup.POLYMER },
  { id: 11, name: "รองเท้ายาง/Crocs", material: "EVA", group: MaterialGroup.POLYMER },
  { id: 12, name: "สายสะพายกระเป๋า", material: "ไนลอน", group: MaterialGroup.POLYMER },
  { id: 13, name: "เชือกไนลอน", material: "ไนลอน", group: MaterialGroup.POLYMER },
  { id: 14, name: "เสื้อกีฬา Dry-Fit", material: "โพลีเอสเตอร์", group: MaterialGroup.POLYMER },
  { id: 15, name: "เสื้อกันฝน", material: "PVC", group: MaterialGroup.POLYMER },
  { id: 16, name: "ถุงมือยาง", material: "ยาง", group: MaterialGroup.POLYMER },
  { id: 17, name: "ลูกฟุตบอล", material: "ยางสังเคราะห์", group: MaterialGroup.POLYMER },
  { id: 18, name: "ลูกบาสเกตบอล", material: "ยางสังเคราะห์", group: MaterialGroup.POLYMER },
  { id: 19, name: "แผ่นรองเมาส์", material: "ยาง/โฟม", group: MaterialGroup.POLYMER },
  { id: 20, name: "กล่องสบู่พลาสติก", material: "PP", group: MaterialGroup.POLYMER },
  { id: 21, name: "แก้วกาแฟพลาสติก", material: "PP", group: MaterialGroup.POLYMER },
  { id: 22, name: "ฟองน้ำล้างจาน", material: "โฟม", group: MaterialGroup.POLYMER },
  { id: 23, name: "แปรงสีฟัน (ด้าม)", material: "PP", group: MaterialGroup.POLYMER },
  { id: 24, name: "กระเป๋านักเรียนผ้าใบ", material: "ไนลอน", group: MaterialGroup.POLYMER },
  { id: 25, name: "ชามเมลามีน", material: "เมลามีน", group: MaterialGroup.POLYMER },
  { id: 26, name: "ช้อนส้อมพลาสติก", material: "PP", group: MaterialGroup.POLYMER },
  { id: 27, name: "ปลอกสายไฟ", material: "PVC", group: MaterialGroup.POLYMER },
  { id: 28, name: "สายหูฟัง", material: "พลาสติก/ยาง", group: MaterialGroup.POLYMER },
  { id: 29, name: "เทปกาว", material: "พลาสติก", group: MaterialGroup.POLYMER },
  { id: 30, name: "โฟมกันกระแทก", material: "โฟม", group: MaterialGroup.POLYMER },
  { id: 31, name: "แผ่นโฟมรองอาหาร", material: "โฟม", group: MaterialGroup.POLYMER },
  { id: 32, name: "กระบองไฟจราจร", material: "ABS", group: MaterialGroup.POLYMER },
  { id: 33, name: "ขาแว่นพลาสติก", material: "พลาสติก", group: MaterialGroup.POLYMER },
  { id: 34, name: "เคสแอร์พอต", material: "ซิลิโคน", group: MaterialGroup.POLYMER },
  { id: 35, name: "เสื้อยืดกีฬา", material: "โพลีเอสเตอร์", group: MaterialGroup.POLYMER },
  { id: 36, name: "โฟมรองเท้า", material: "EVA", group: MaterialGroup.POLYMER },
  { id: 37, name: "ป้ายไวนิล", material: "PVC", group: MaterialGroup.POLYMER },
  { id: 38, name: "ถังน้ำพลาสติก", material: "PE", group: MaterialGroup.POLYMER },
  { id: 39, name: "กระติ๊บพลาสติก", material: "PP", group: MaterialGroup.POLYMER },
  { id: 40, name: "ขวดแชมพู", material: "HDPE", group: MaterialGroup.POLYMER },

  // Ceramic
  { id: 41, name: "ถ้วยเซรามิก", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 42, name: "ชามเซรามิก", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 43, name: "แก้วน้ำ", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 44, name: "แจกันดินเผา", material: "ดินเผา", group: MaterialGroup.CERAMIC },
  { id: 45, name: "อิฐมอญ", material: "ดินเผา", group: MaterialGroup.CERAMIC },
  { id: 46, name: "กระเบื้องพื้น", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 47, name: "กระเบื้องหลังคา", material: "ดินเผา", group: MaterialGroup.CERAMIC },
  { id: 48, name: "โถสุขภัณฑ์", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 49, name: "อ่างล้างหน้า", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 50, name: "กระจกเงา", material: "กระจก", group: MaterialGroup.CERAMIC },
  { id: 51, name: "ขวดโหลแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 52, name: "ลูกแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 53, name: "หลอดไฟแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 54, name: "จานเคลือบ", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 55, name: "ครกดินเผา", material: "ดินเผา", group: MaterialGroup.CERAMIC },
  { id: 56, name: "ครกหิน", material: "หิน", group: MaterialGroup.CERAMIC },
  { id: 57, name: "หินแกรนิต", material: "หิน", group: MaterialGroup.CERAMIC },
  { id: 58, name: "หินอ่อน", material: "หิน", group: MaterialGroup.CERAMIC },
  { id: 59, name: "กระถางต้นไม้ดินเผา", material: "ดินเผา", group: MaterialGroup.CERAMIC },
  { id: 60, name: "กระปุกเครื่องปรุงแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 61, name: "หลอดทดลองแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 62, name: "ฉนวนไฟฟ้าเซรามิก", material: "เซรามิก", group: MaterialGroup.CERAMIC },
  { id: 63, name: "ขวดน้ำแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 64, name: "จานแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 65, name: "ฝาครอบเตาแก้ว", material: "กระจกทนร้อน", group: MaterialGroup.CERAMIC },
  { id: 66, name: "แก้วกาแฟแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 67, name: "ขวดน้ำหอมแก้ว", material: "แก้ว", group: MaterialGroup.CERAMIC },
  { id: 68, name: "หน้าเตารีดแก้วเคลือบ", material: "กระจกเคลือบ", group: MaterialGroup.CERAMIC },
  { id: 69, name: "ไฟเบอร์กลาส", material: "แก้วผสม", group: MaterialGroup.CERAMIC },

  // Metal
  { id: 70, name: "ช้อนสแตนเลส", material: "สแตนเลส", group: MaterialGroup.METAL },
  { id: 71, name: "ส้อมสแตนเลส", material: "สแตนเลส", group: MaterialGroup.METAL },
  { id: 72, name: "มีดทำครัว", material: "เหล็ก/สแตนเลส", group: MaterialGroup.METAL },
  { id: 73, name: "หม้อสแตนเลส", material: "สแตนเลส", group: MaterialGroup.METAL },
  { id: 74, name: "กระทะอลูมิเนียม", material: "อะลูมิเนียม", group: MaterialGroup.METAL },
  { id: 75, name: "กระทะเหล็ก", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 76, name: "ประตูเหล็ก", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 77, name: "กุญแจ", material: "เหล็ก/สแตนเลส", group: MaterialGroup.METAL },
  { id: 78, name: "น็อตและสกรู", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 79, name: "ค้อน", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 80, name: "คีม", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 81, name: "ไขควง", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 82, name: "ตะปู", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 83, name: "กรอบหน้าต่างอลูมิเนียม", material: "อะลูมิเนียม", group: MaterialGroup.METAL },
  { id: 84, name: "กระป๋องน้ำอัดลม", material: "อะลูมิเนียม", group: MaterialGroup.METAL },
  { id: 85, name: "กระป๋องอาหาร", material: "เหล็กเคลือบดีบุก", group: MaterialGroup.METAL },
  { id: 86, name: "สายไฟ", material: "ทองแดง", group: MaterialGroup.METAL },
  { id: 87, name: "ขาโต๊ะเหล็ก", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 88, name: "โครงเตียงเหล็ก", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 89, name: "ขาตั้งไมค์", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 90, name: "กรรไกร", material: "สแตนเลส", group: MaterialGroup.METAL },
  { id: 91, name: "เหรียญบาท", material: "โลหะผสม", group: MaterialGroup.METAL },
  { id: 92, name: "ที่เปิดขวดโลหะ", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 93, name: "กระดิ่ง", material: "ทองเหลือง", group: MaterialGroup.METAL },
  { id: 94, name: "ท่อเหล็ก", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 95, name: "ที่หนีบผ้าโลหะ", material: "สแตนเลส", group: MaterialGroup.METAL },
  { id: 96, name: "โครงร่ม", material: "เหล็ก", group: MaterialGroup.METAL },
  { id: 97, name: "ไมโครโฟน (ตัวถัง)", material: "อะลูมิเนียม", group: MaterialGroup.METAL },
  { id: 98, name: "ลำโพง (กรอบอลูมิเนียม)", material: "อะลูมิเนียม", group: MaterialGroup.METAL },
  { id: 99, name: "หมวกกันน็อกบางรุ่น (โครงภายใน)", material: "อลูมิเนียม", group: MaterialGroup.METAL },
];